sudo: required
language: node_js
node_js:
   - "8"
branches:
  only:
    - master
    - develop
services:
  - docker
before_install:
  - docker build -t frocher/bnb_app .
before_script:
  - npm install -g polymer-cli
  - npm install gulp-cli -g
